/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
   // https://mvnrepository.com/artifact/org.springframework/spring-context-support
implementation("org.springframework:spring-context-support:6.1.12")
// https://mvnrepository.com/artifact/org.springframework/spring-jdbc
implementation("org.springframework:spring-jdbc:6.1.12")
// https://mvnrepository.com/artifact/org.springframework/spring-tx
implementation("org.springframework:spring-tx:6.1.12")
// https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
implementation("com.mysql:mysql-connector-j:8.3.0")
// https://mvnrepository.com/artifact/org.postgresql/postgresql
implementation("org.postgresql:postgresql:42.4.5")
// https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2
implementation("org.apache.commons:commons-dbcp2:2.12.0")
// https://mvnrepository.com/artifact/com.zaxxer/HikariCP
implementation("com.zaxxer:HikariCP:5.1.0")
// https://mvnrepository.com/artifact/io.github.m-m-m/mmm-orm-jdbc-pool-c3po
implementation("io.github.m-m-m:mmm-orm-jdbc-pool-c3po:0.9.8")




}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


